mod.id = "siegeworks"
mod.name = "Siegeworks"
mod.version = "0.1.0-beta.9"
mod.group = "me.mss1r"
mod.authors = "mss1r"
mod.license = "LGPL-3.0-only (code); custom terms (assets)"
mod.description = "Build and operate medieval siege engines in Minecraft."

[forge."1.20.1"]
mod.minecraft_range = "[1.20.1,1.21)"
mod.forge_range = "[47.4.10,)"
mod.loader_range = "[47,)"
mod.pack_format = "15"
deps.forge = "1.20.1-47.4.10"
deps.architectury = "9.2.14"
deps.axiomata = "30ec9272d5f7a10b54351e7ade15b8358932cd2b"
deps.axiomata_mod = "0.1.0-beta.8"
deps.geckolib = "4.8.4"
deps.recruits = "1.15.2"
deps.recruits_range = "[1.15.2,1.16.0)"
deps.rts_command = "21a4b88"
deps.rts_command_range = "[0.1.0-beta.2,)"

[neoforge."1.21.1"]
mod.minecraft_range = "[1.21.1]"
mod.loader_range = "[1,)"
mod.pack_format = "34"
deps.neoforge = "21.1.248"
deps.architectury = "13.0.11"
deps.axiomata = "30ec9272d5f7a10b54351e7ade15b8358932cd2b"
deps.axiomata_mod = "0.1.0-beta.8"
deps.geckolib = "4.9.2"
deps.recruits = "ecfe4b59167bb72460ce7b015ff6391eb39d0463"
deps.recruits_range = "[1.15.2,)"
