modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/mess1re/siegeworks/main/updates/neoforge.json"
logoFile="siegeworks.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.recruits.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="recruits"
type="optional"
versionRange="${recruits_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="axiomata"
type="required"
versionRange="[${axiomata_mod_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[${architectury_version},)"
ordering="AFTER"
side="BOTH"
